# This file was generated by @liquid-labs/sdlc-projects-workflow-local-node-build.
# Refer to https://npmjs.com/package/@liquid-labs/sdlc-projects-workflow-local-
# node-build for further details

SDLC_BABEL:=npx babel
SDLC_BABEL_CONFIG:=$(shell npm explore @liquid-labs/sdlc-resource-babel-and-rollup -- pwd)/dist/babel/babel.config.cjs

SDLC_ROLLUP:=npx rollup
SDLC_ROLLUP_CONFIG:=$(shell npm explore @liquid-labs/sdlc-resource-babel-and-rollup -- pwd)/dist/rollup/rollup.config.mjs

# Node 
SDLC_NODE_MAJOR_VERSION:=$(shell echo $$(node --version) | sed -Ee 's/^v([0-9]+).*/\1/')
SDLC_JEST:=$(shell if [ "$(SDLC_NODE_MAJOR_VERSION)" -ge "25" ]; then echo NODE_OPTIONS="'$$NODE_OPTIONS --no-webstorage' "; fi)npx jest
SDLC_JEST_CONFIG:=$(shell npm explore @liquid-labs/sdlc-resource-jest -- pwd)/dist/jest.config.js

SDLC_ESLINT:=npx fandl
